In [74]:
import pandas as pd
import os
import numpy as np

In [75]:
pwd

'C:\\Users\\Dcode\\AppData\\Local\\Programs\\Python\\Python39\\Scripts'

In [76]:
from sklearn.preprocessing import LabelEncoder
dataset = pd.read_csv("SalaryPrediction.csv")
dataset.isnull().sum()
handle= dataset['Salary'].median()
handle
dataset = dataset.dropna()

dataset[['Gender', 'Degree']] = dataset[['Gender','Degree']].apply(LabelEncoder().fit_transform)
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, 10]

In [77]:
handle

30000.0

In [78]:
dataset.Salary=dataset.Salary.fillna(handle)

In [79]:
dataset

Gender  CGPA  Degree  Graduation Year  Coding Skill  \
0         1  3.50       1             2018            70   
1         0  3.80       0             2022            50   
2         1  3.50       0             2022             5   
3         0  3.57       0             2022            65   
4         1  3.50       0             2022            20   
..      ...   ...     ...              ...           ...   
308       1  3.30       0             2022            60   
309       1  3.25       0             2022            50   
310       1  3.40       0             2022            70   
311       1  3.07       0             2022            50   
312       1  3.59       0             2019            72   

     Problem-solving Skill  Software development Skill  Communication Skill  \
0                       60                          80                   70   
1                       30                          10                   10   
2                        5                           5                   62   
3                       70                          65                   70   
4                       30                          50                   80   
..                     ...                         ...                  ...   
308                     65                          68                   95   
309                     55                          45                   70   
310                     60                          70                  100   
311                     50                          50                   20   
312                     78                          67                   81   

     Research  Years Of Experience  Salary  
0          50                    3   50000  
1          10                    0   20000  
2          64                    0   30000  
3          75                    1   20000  
4          15                    1   40000  
..        ...                  ...     ...  
308        90                    1   35000  
309        40                    0   25000  
310        70                    0   50000  
311        20                    1   50000  
312        80                    3   63000  

[313 rows x 11 columns]

In [170]:
dataset.nunique()

Gender                         2
CGPA                          44
Degree                         2
Graduation Year                9
Coding Skill                  21
Problem-solving Skill         22
Software development Skill    22
Communication Skill           26
Research                      24
Years Of Experience            6
Salary                        23
dtype: int64

In [171]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn import metrics

# predicting the accuracy score
print('model performance Of Multiple Linear Regression')
score=r2_score(y_test,y_pred)
print('r2 socre is ',score)
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))


model performance Of Multiple Linear Regression
r2 socre is  0.1752905066878534
Mean Absolute Error: 9250.587279295962
Mean Squared Error: 125727471.3353709
Root Mean Squared Error: 11212.826197501276


In [179]:
import matplotlib.pyplot as plt
%matplotlib inline

In [180]:
dataset['Salary'].value_counts()

30000    59
20000    49
50000    35
25000    32
40000    25
35000    24
27000    14
51000    10
45000     9
34000     7
63000     7
33000     5
10000     5
36500     4
41000     4
32000     4
56000     4
43000     4
60500     4
12000     2
55000     2
71000     2
60000     2
Name: Salary, dtype: int64

In [181]:
x1=dataset[['Years Of Experience']]

In [182]:
x1

Years Of Experience
0                      3
1                      0
2                      0
3                      1
4                      1
..                   ...
308                    1
309                    0
310                    0
311                    1
312                    3

[313 rows x 1 columns]

In [183]:
y=dataset['Salary']
#y=y.astype('int')

In [184]:
y

0      50000
1      20000
2      30000
3      20000
4      40000
       ...  
308    35000
309    25000
310    50000
311    50000
312    63000
Name: Salary, Length: 313, dtype: int64

In [185]:
#X_train, X_test, ytrain, ytest = train_test_split(x1, y, test_size = 0.3, random_state = 1)
x_train, X_test, y_train, y_test = train_test_split(x1, y, test_size = 0.5, random_state = 1)

In [186]:
X_test

Years Of Experience
80                     1
268                    1
310                    0
187                    0
105                    0
..                   ...
228                    0
40                     2
21                     0
101                    2
69                     3

[157 rows x 1 columns]

In [187]:
y_test

80     30000
268    20000
310    50000
187    27000
105    30000
       ...  
228    30000
40     50000
21     30000
101    55000
69     45000
Name: Salary, Length: 157, dtype: int64

In [188]:
from sklearn.linear_model import LogisticRegression

In [189]:
model2 = LogisticRegression()

In [190]:
model2.fit(x_train,y_train)

LogisticRegression()

In [191]:
y5=model2.predict(X_test)

In [192]:
y0=model2.score(X_test,y_test)
print('r2 socre is ',y0)

r2 socre is  0.09554140127388536


In [193]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y5))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y5))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y5)))


Mean Absolute Error: 11506.369426751593
Mean Squared Error: 196800955.41401273
Root Mean Squared Error: 14028.576385863704


In [31]:
model2.predict_proba(X_test)

array([[0.00647945, 0.1777028 , 0.16074838, ..., 0.01225277, 0.00337433,
        0.0100552 ],
       [0.00647945, 0.1777028 , 0.16074838, ..., 0.01225277, 0.00337433,
        0.0100552 ],
       [0.00259245, 0.24239946, 0.15445891, ..., 0.0045552 , 0.00055375,
        0.00230144],
       ...,
       [0.00259245, 0.24239946, 0.15445891, ..., 0.0045552 , 0.00055375,
        0.00230144],
       [0.01165756, 0.09377749, 0.12042646, ..., 0.02372478, 0.01480133,
        0.03162446],
       [0.01309444, 0.03089672, 0.05632571, ..., 0.02868003, 0.04053429,
        0.06209617]])

In [97]:
X = dataset.drop('Salary' , axis=1)
Y = dataset['Salary']

print('Shape of X = ', X.shape)
print('Shape of Y = ', Y.shape)

Shape of X =  (313, 10)
Shape of Y =  (313,)


In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (187, 10)
Shape of y_train =  (187,)
Shape of X_test =  (126, 10)
Shape of y_test =  (126,)


In [99]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [100]:
from sklearn.preprocessing import PolynomialFeatures

In [101]:
poly_reg = PolynomialFeatures(degree=2)
poly_reg.fit(X_train)
X_train_poly = poly_reg.transform(X_train)
X_test_poly = poly_reg.transform(X_test) 

In [102]:
X_train_poly.shape, X_test_poly.shape

((187, 66), (126, 66))

In [103]:
lr = LinearRegression()

In [104]:
lr.fit(X_train_poly, y_train)

LinearRegression()

In [105]:
#lr.score(X_test_poly, y_test,)

In [106]:
lr.predict([X_test_poly[0,:]])

array([56960.])

In [107]:
y_pred = lr.predict(X_test_poly)
y_pred

array([ 5.69600000e+04,  3.36240000e+04,  2.71580000e+04,  2.55700000e+04,
        6.27240000e+04,  3.04000000e+04,  5.03600000e+04,  2.49080000e+04,
        3.49940000e+04,  2.49080000e+04,  1.00820000e+04,  2.08440000e+04,
        4.98240000e+04,  3.87620000e+04,  4.02340000e+04,  3.49940000e+04,
        2.93800000e+04,  2.94160000e+04,  3.12280000e+04, -1.37689448e+14,
        3.16780000e+04,  2.71580000e+04,  5.01000000e+04,  5.12860000e+04,
        1.00820000e+04,  5.01000000e+04,  3.04000000e+04,  4.91720000e+04,
        3.36240000e+04,  3.74520000e+04,  3.48880000e+04,  2.95860000e+04,
        2.01720000e+04,  3.04000000e+04,  2.20080000e+04,  4.54140000e+04,
        4.91720000e+04,  1.92040000e+04,  1.92040000e+04,  3.22620000e+04,
        3.06660000e+04,  5.09640000e+04,  2.61580000e+04,  4.58900000e+04,
        3.97220000e+04, -1.37689448e+14,  1.99024000e+05,  2.49080000e+04,
        4.91720000e+04,  3.29900000e+04, -1.37689448e+14,  4.17420000e+04,
        2.95860000e+04,  

In [108]:
y_test

23     56000
160    30000
90     27000
115    25000
118    63000
       ...  
26     35000
211    35000
99     27000
298    30000
7      30000
Name: Salary, Length: 126, dtype: int64

In [109]:
#score=absolute(r2_score(y_test, y_pred))
#mae = metrics.mean_absolute_error(y_test, y_pred)
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

Mean Absolute Error: 437370661968730.25


In [110]:
#print('MAE for Polynomial = ',mae)
print('R2-Score for Polynomial = ',score)
print('MSE for Polynomial = ',mse)
print('RMSE for Polynomial = ',rmse)

R2-Score for Polynomial =  0.1752905066878534
MSE for Polynomial =  1.1812385304816415e+31
RMSE for Polynomial =  3436915085482388.5


In [111]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [112]:
X_train.shape

(234, 10)

In [113]:
y_train.shape

(234,)

In [114]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=1.0)

In [115]:
lasso.fit(X_train, y_train)

Lasso()

In [116]:
y_pred = lasso.predict(X_test)

In [117]:
y_pred

array([23333.81694392, 28757.66491261, 31696.90670189, 31988.00820856,
       27681.36729166, 40312.73436353, 43518.60930562, 28967.44000342,
       35643.58795283, 29743.1626435 , 46896.29238913, 41217.27710605,
       33021.8660148 , 35614.67649573, 34281.06971177, 21333.02498073,
       29452.14482304, 39557.28249519, 27818.79946802, 31962.99435722,
       35643.58795283, 25890.21663425, 28743.4164186 , 35643.58795283,
       34982.54843863, 44294.97497376, 26745.37049491, 46896.29238913,
       28743.4164186 , 41217.27710605, 40188.40714709, 31988.00820856,
       45533.41899352, 31988.00820856, 49735.75536119, 28967.44000342,
       30747.24574967, 31696.90670189, 36022.91020887, 35643.58795283,
       43518.60930562, 43950.71255863, 39477.84490755, 49735.75536119,
       23336.6546887 , 26618.15167938, 27341.36352888, 31962.99435722,
       24019.20439648, 27341.36352888, 34276.48842573, 35614.67649573,
       40793.72468817, 26837.81727101, 24019.20439648, 36445.62012977,
      

In [118]:
print("Slope: %.2f " % lasso.coef_[0])

Slope: -183.07 


In [119]:
print("Intercept: %.2f " % lasso.intercept_)

Intercept: -810778.44 


In [120]:
from sklearn.metrics import mean_squared_error
mae = metrics.mean_absolute_error(y_test, y_pred)
mse= mean_squared_error(y_test, y_pred)
rmse= np.sqrt(mean_squared_error(y_test, y_pred))

In [121]:
print('MAE for Lasso = ',mae)
print("MSE for Lasso =", mse)
print("RMSE for Lasso =", rmse)
print("R2 for Lasso = %.2f " % lasso.score(X_test, y_test))

MAE for Lasso =  6899.365021449132
MSE for Lasso = 80438542.17290261
RMSE for Lasso = 8968.753657722047
R2 for Lasso = 0.49 


In [122]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,random_state=100)

In [123]:
X_train.shape

(234, 10)

In [124]:
Y_train.shape

(234,)

In [125]:
from sklearn.ensemble import RandomForestRegressor

In [126]:
rf = RandomForestRegressor()

In [127]:
rf.fit(X_train, Y_train)

RandomForestRegressor()

In [133]:
Y_pred = rf.predict(X_test)

In [134]:
Y_pred

array([49150.        , 30000.        , 28860.        , 39650.        ,
       25500.        , 28680.        , 23011.42316017, 20070.        ,
       30000.        , 20383.94300144, 37940.        , 25500.        ,
       35000.        , 65790.        , 51000.        , 20520.        ,
       49205.        , 29165.        , 29165.        , 23011.42316017,
       40575.        , 25100.        , 49205.        , 26030.        ,
       25000.        , 30000.        , 36375.        , 49150.        ,
       30080.        , 32060.        , 20383.94300144, 49150.        ,
       30080.        , 30000.        , 40990.        , 63000.        ,
       36060.        , 49150.        , 63000.        , 36375.        ,
       49700.        , 27000.        , 30000.        , 40990.        ,
       49700.        , 50000.        , 37940.        , 21455.        ,
       29165.        , 45000.        , 25000.        , 45000.        ,
       25100.        , 25000.        , 50000.        , 51000.        ,
      

In [138]:
#from sklearn.metrics import mean_squared_error
#mean_squared_error(Y_test, Y_pred)

In [139]:
#np.sqrt(mean_squared_error(Y_test, Y_pred))

In [140]:
score=r2_score(Y_test,Y_pred)
print('r2 socre is ',score)
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

r2 socre is  0.9400320529505105
Mean Absolute Error: 1382.708641569401
Mean Squared Error: 8498935.91621345
Root Mean Squared Error: 2915.2934528471483


In [161]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y, random_state=99)

In [162]:
from sklearn.svm import SVR

In [163]:
sc1 = StandardScaler()
sc1.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [164]:
svr_rbf = SVR(kernel = 'rbf')
svr_rbf.fit(X_train, y_train)
Y_pred1 = svr_rbf.predict(X_test)
svr_rbf.score(X_test, y_test)

-0.14517115539525327

In [167]:
X_test[0]

array([-1.19522861,  0.30785088, -0.23769134,  0.47220358,  0.35143658,
        0.13092797,  0.20712621, -0.30220255, -0.69549687, -0.8653171 ])

In [194]:
print('model performance Of SVR')
score2=r2_score(Y_test,Y_pred1)
print('r2 socre is ',score2)
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred1))  
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred1))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred1)))

model performance Of SVR
r2 socre is  -0.17525054101164161
Mean Absolute Error: 9702.290202196218
Mean Squared Error: 166561963.93233305
Root Mean Squared Error: 12905.888730821021
